package tpv.cirer.com.marivent.modelo;

/**
 * Created by JUAN on 03/09/2017.
 */

public class Param {
    private String DEFAULT_ESTADO_TODOS_GRUPO;
    private String DEFAULT_ESTADO_TODOS_EMPRESA;
    private String DEFAULT_ESTADO_TODOS_LOCAL;
    private String DEFAULT_ESTADO_TODOS_SECCION;
    private String DEFAULT_ESTADO_TODOS_CAJA;
    private String DEFAULT_ESTADO_TODOS_TURNO;
    private String DEFAULT_ESTADO_TODOS_MESA;
    private String DEFAULT_ESTADO_TODOS_EMPLEADO;
    private String DEFAULT_ESTADO_TODOS_TIPOPLATO;
    private String DEFAULT_ESTADO_OPEN_PEDIDO;
    private String DEFAULT_ESTADO_OPEN_FACTURA;
    private String DEFAULT_ESTADO_CLOSE_PEDIDO;
    private String DEFAULT_ESTADO_CLOSE_FACTURA;
    private String DEFAULT_ESTADO_COBRO_FACTURA;
    private String DEFAULT_TIPO_COBRO_OPEN_FACTURA;
    private String DEFAULT_TABLA_OPEN_PEDIDO;
    private String DEFAULT_TABLA_OPEN_FACTURA;
    private String DEFAULT_TABLA_OPEN_FACTURA_CLIENTES;
    private String DEFAULT_TIPO_ARTICULO_BUFFET;
    private String DEFAULT_TIPO_MESA_BUFFET;
    private String DEFAULT_TIPO_COBRO_BUFFET;
    private String DEFAULT_SERIE_BUFFET;
    private String DEFAULT_TIPO_SERIE_FACTURA_CLIENTE;
    private int DEFAULT_VALOR_ON_APERTURA;
    private int DEFAULT_VALOR_ON_ACTIVO;
    private int DEFAULT_VALOR_OFF_APERTURA;
    private int DEFAULT_VALOR_OFF_ACTIVO;
    
    public Param(){}
    
    public Param(String DEFAULT_ESTADO_TODOS_GRUPO,
            String DEFAULT_ESTADO_TODOS_EMPRESA,
            String DEFAULT_ESTADO_TODOS_LOCAL,
            String DEFAULT_ESTADO_TODOS_SECCION,
            String DEFAULT_ESTADO_TODOS_CAJA,
            String DEFAULT_ESTADO_TODOS_TURNO,
            String DEFAULT_ESTADO_TODOS_MESA,
            String DEFAULT_ESTADO_TODOS_EMPLEADO,
            String DEFAULT_ESTADO_TODOS_TIPOPLATO,
            String DEFAULT_ESTADO_OPEN_PEDIDO,
            String DEFAULT_ESTADO_OPEN_FACTURA,
            String DEFAULT_ESTADO_CLOSE_PEDIDO,
            String DEFAULT_ESTADO_CLOSE_FACTURA,
            String DEFAULT_ESTADO_COBRO_FACTURA,
            String DEFAULT_TIPO_COBRO_OPEN_FACTURA,
            String DEFAULT_TABLA_OPEN_PEDIDO,
            String DEFAULT_TABLA_OPEN_FACTURA,
            String DEFAULT_TABLA_OPEN_FACTURA_CLIENTES,
            String DEFAULT_TIPO_ARTICULO_BUFFET,     
            String DEFAULT_TIPO_MESA_BUFFET,
            String DEFAULT_TIPO_COBRO_BUFFET,
            String DEFAULT_SERIE_BUFFET,
            String DEFAULT_TIPO_SERIE_FACTURA_CLIENTE,     
            int DEFAULT_VALOR_ON_APERTURA,
            int DEFAULT_VALOR_ON_ACTIVO,
            int DEFAULT_VALOR_OFF_APERTURA,
            int DEFAULT_VALOR_OFF_ACTIVO){
        this.DEFAULT_ESTADO_TODOS_GRUPO=DEFAULT_ESTADO_TODOS_GRUPO;
        this.DEFAULT_ESTADO_TODOS_EMPRESA=DEFAULT_ESTADO_TODOS_EMPRESA;
        this.DEFAULT_ESTADO_TODOS_LOCAL=DEFAULT_ESTADO_TODOS_LOCAL;
        this.DEFAULT_ESTADO_TODOS_SECCION=DEFAULT_ESTADO_TODOS_SECCION;
        this.DEFAULT_ESTADO_TODOS_CAJA=DEFAULT_ESTADO_TODOS_CAJA;
        this.DEFAULT_ESTADO_TODOS_TURNO=DEFAULT_ESTADO_TODOS_TURNO;
        this.DEFAULT_ESTADO_TODOS_MESA=DEFAULT_ESTADO_TODOS_MESA;
        this.DEFAULT_ESTADO_TODOS_EMPLEADO=DEFAULT_ESTADO_TODOS_EMPLEADO;
        this.DEFAULT_ESTADO_TODOS_TIPOPLATO=DEFAULT_ESTADO_TODOS_TIPOPLATO;
        this.DEFAULT_ESTADO_OPEN_PEDIDO=DEFAULT_ESTADO_OPEN_PEDIDO;
        this.DEFAULT_ESTADO_OPEN_FACTURA=DEFAULT_ESTADO_OPEN_FACTURA;
        this.DEFAULT_ESTADO_CLOSE_PEDIDO=DEFAULT_ESTADO_CLOSE_PEDIDO;
        this.DEFAULT_ESTADO_CLOSE_FACTURA=DEFAULT_ESTADO_CLOSE_FACTURA;
        this.DEFAULT_ESTADO_COBRO_FACTURA=DEFAULT_ESTADO_COBRO_FACTURA;
        this.DEFAULT_TIPO_COBRO_OPEN_FACTURA=DEFAULT_TIPO_COBRO_OPEN_FACTURA;
        this.DEFAULT_TABLA_OPEN_PEDIDO=DEFAULT_TABLA_OPEN_PEDIDO;
        this.DEFAULT_TABLA_OPEN_FACTURA=DEFAULT_TABLA_OPEN_FACTURA;
        this.DEFAULT_TABLA_OPEN_FACTURA_CLIENTES=DEFAULT_TABLA_OPEN_FACTURA_CLIENTES;
        this.DEFAULT_TIPO_ARTICULO_BUFFET=DEFAULT_TIPO_ARTICULO_BUFFET;
        this.DEFAULT_TIPO_MESA_BUFFET=DEFAULT_TIPO_MESA_BUFFET;
        this.DEFAULT_TIPO_COBRO_BUFFET=DEFAULT_TIPO_COBRO_BUFFET;
        this.DEFAULT_SERIE_BUFFET=DEFAULT_SERIE_BUFFET;
        this.DEFAULT_TIPO_SERIE_FACTURA_CLIENTE=DEFAULT_TIPO_SERIE_FACTURA_CLIENTE;
        this.DEFAULT_VALOR_ON_APERTURA=DEFAULT_VALOR_ON_APERTURA;
        this.DEFAULT_VALOR_ON_ACTIVO=DEFAULT_VALOR_ON_ACTIVO;
        this.DEFAULT_VALOR_OFF_APERTURA=DEFAULT_VALOR_OFF_APERTURA;
        this.DEFAULT_VALOR_OFF_ACTIVO=DEFAULT_VALOR_OFF_ACTIVO;

    }
     public void setDEFAULT_ESTADO_TODOS_GRUPO(String DEFAULT_ESTADO_TODOS_GRUPO) {
        this.DEFAULT_ESTADO_TODOS_GRUPO = DEFAULT_ESTADO_TODOS_GRUPO;
    }
    public String getDEFAULT_ESTADO_TODOS_GRUPO() {
        return DEFAULT_ESTADO_TODOS_GRUPO;
    }
    public void setDEFAULT_ESTADO_TODOS_EMPRESA(String DEFAULT_ESTADO_TODOS_EMPRESA) {
        this.DEFAULT_ESTADO_TODOS_EMPRESA = DEFAULT_ESTADO_TODOS_EMPRESA;
    }
    public String getDEFAULT_ESTADO_TODOS_EMPRESA() {
        return DEFAULT_ESTADO_TODOS_EMPRESA;
    }
    public void setDEFAULT_ESTADO_TODOS_LOCAL(String DEFAULT_ESTADO_TODOS_LOCAL) {
        this.DEFAULT_ESTADO_TODOS_LOCAL = DEFAULT_ESTADO_TODOS_LOCAL;
    }
    public String getDEFAULT_ESTADO_TODOS_LOCAL() {
        return DEFAULT_ESTADO_TODOS_LOCAL;
    }
    public void setDEFAULT_ESTADO_TODOS_SECCION(String DEFAULT_ESTADO_TODOS_SECCION) {
        this.DEFAULT_ESTADO_TODOS_SECCION = DEFAULT_ESTADO_TODOS_SECCION;
    }
    public String getDEFAULT_ESTADO_TODOS_SECCION() {
        return DEFAULT_ESTADO_TODOS_SECCION;
    }
    public void setDEFAULT_ESTADO_TODOS_CAJA(String DEFAULT_ESTADO_TODOS_CAJA) {
        this.DEFAULT_ESTADO_TODOS_CAJA = DEFAULT_ESTADO_TODOS_CAJA;
    }
    public String getDEFAULT_ESTADO_TODOS_CAJA() {
        return DEFAULT_ESTADO_TODOS_CAJA;
    }
    public void setDEFAULT_ESTADO_TODOS_TURNO(String DEFAULT_ESTADO_TODOS_TURNO) {
        this.DEFAULT_ESTADO_TODOS_TURNO = DEFAULT_ESTADO_TODOS_TURNO;
    }
    public String getDEFAULT_ESTADO_TODOS_TURNO() {
        return DEFAULT_ESTADO_TODOS_TURNO;
    }
    public void setDEFAULT_ESTADO_TODOS_MESA(String DEFAULT_ESTADO_TODOS_MESA) {
        this.DEFAULT_ESTADO_TODOS_MESA = DEFAULT_ESTADO_TODOS_MESA;
    }
    public String getDEFAULT_ESTADO_TODOS_MESA() {
        return DEFAULT_ESTADO_TODOS_MESA;
    }
    public void setDEFAULT_ESTADO_TODOS_EMPLEADO(String DEFAULT_ESTADO_TODOS_EMPLEADO) {
        this.DEFAULT_ESTADO_TODOS_EMPLEADO = DEFAULT_ESTADO_TODOS_EMPLEADO;
    }
    public String getDEFAULT_ESTADO_TODOS_EMPLEADO() {
        return DEFAULT_ESTADO_TODOS_EMPLEADO;
    }
    public void setDEFAULT_ESTADO_TODOS_TIPOPLATO(String DEFAULT_ESTADO_TODOS_TIPOPLATO) {
        this.DEFAULT_ESTADO_TODOS_TIPOPLATO = DEFAULT_ESTADO_TODOS_TIPOPLATO;
    }
    public String getDEFAULT_ESTADO_TODOS_TIPOPLATO() {
        return DEFAULT_ESTADO_TODOS_TIPOPLATO;
    }

    public void setDEFAULT_ESTADO_OPEN_PEDIDO(String DEFAULT_ESTADO_OPEN_PEDIDO) {
        this.DEFAULT_ESTADO_OPEN_PEDIDO = DEFAULT_ESTADO_OPEN_PEDIDO;
    }
    public String getDEFAULT_ESTADO_OPEN_PEDIDO() {
        return DEFAULT_ESTADO_OPEN_PEDIDO;
    }
    public void setDEFAULT_ESTADO_OPEN_FACTURA(String DEFAULT_ESTADO_OPEN_FACTURA) {
        this.DEFAULT_ESTADO_OPEN_FACTURA = DEFAULT_ESTADO_OPEN_FACTURA;
    }
    public String getDEFAULT_ESTADO_OPEN_FACTURA() {
        return DEFAULT_ESTADO_OPEN_FACTURA;
    }
    public void setDEFAULT_ESTADO_CLOSE_PEDIDO(String DEFAULT_ESTADO_CLOSE_PEDIDO) {
        this.DEFAULT_ESTADO_CLOSE_PEDIDO = DEFAULT_ESTADO_CLOSE_PEDIDO;
    }
    public String getDEFAULT_ESTADO_CLOSE_PEDIDO() {
        return DEFAULT_ESTADO_CLOSE_PEDIDO;
    }
    public void setDEFAULT_ESTADO_CLOSE_FACTURA(String DEFAULT_ESTADO_CLOSE_FACTURA) {
        this.DEFAULT_ESTADO_CLOSE_FACTURA = DEFAULT_ESTADO_CLOSE_FACTURA;
    }
    public String getDEFAULT_ESTADO_CLOSE_FACTURA() {
        return DEFAULT_ESTADO_CLOSE_FACTURA;
    }
    public void setDEFAULT_ESTADO_COBRO_FACTURA(String DEFAULT_ESTADO_COBRO_FACTURA) {
        this.DEFAULT_ESTADO_COBRO_FACTURA = DEFAULT_ESTADO_COBRO_FACTURA;
    }
    public String getDEFAULT_ESTADO_COBRO_FACTURA() {
        return DEFAULT_ESTADO_COBRO_FACTURA;
    }
    public void setDEFAULT_TIPO_COBRO_OPEN_FACTURA(String DEFAULT_TIPO_COBRO_OPEN_FACTURA) {
        this.DEFAULT_TIPO_COBRO_OPEN_FACTURA = DEFAULT_TIPO_COBRO_OPEN_FACTURA;
    }
    public String getDEFAULT_TIPO_COBRO_OPEN_FACTURA() {
        return DEFAULT_TIPO_COBRO_OPEN_FACTURA;
    }
    public void setDEFAULT_TABLA_OPEN_PEDIDO(String DEFAULT_TABLA_OPEN_PEDIDO) {
        this.DEFAULT_TABLA_OPEN_PEDIDO = DEFAULT_TABLA_OPEN_PEDIDO;
    }
    public String getDEFAULT_TABLA_OPEN_PEDIDO() {
        return DEFAULT_TABLA_OPEN_PEDIDO;
    }
    public void setDEFAULT_TABLA_OPEN_FACTURA(String DEFAULT_TABLA_OPEN_FACTURA) {
        this.DEFAULT_TABLA_OPEN_FACTURA = DEFAULT_TABLA_OPEN_FACTURA;
    }
    public String getDEFAULT_TABLA_OPEN_FACTURA() {
        return DEFAULT_TABLA_OPEN_FACTURA;
    }
    public void setDEFAULT_TABLA_OPEN_FACTURA_CLIENTES(String DEFAULT_TABLA_OPEN_FACTURA_CLIENTES) {
        this.DEFAULT_TABLA_OPEN_FACTURA_CLIENTES = DEFAULT_TABLA_OPEN_FACTURA_CLIENTES;
    }
    public String getDEFAULT_TABLA_OPEN_FACTURA_CLIENTES() {
        return DEFAULT_TABLA_OPEN_FACTURA_CLIENTES;
    }
    public void setDEFAULT_VALOR_ON_APERTURA(int DEFAULT_VALOR_ON_APERTURA) {
        this.DEFAULT_VALOR_ON_APERTURA = DEFAULT_VALOR_ON_APERTURA;
    }
    public void setDEFAULT_TIPO_ARTICULO_BUFFET(String DEFAULT_TIPO_ARTICULO_BUFFET) {
        this.DEFAULT_TIPO_ARTICULO_BUFFET = DEFAULT_TIPO_ARTICULO_BUFFET;
    }
    public String getDEFAULT_TIPO_ARTICULO_BUFFET() {
        return DEFAULT_TIPO_ARTICULO_BUFFET;
    }
    
    public void setDEFAULT_TIPO_MESA_BUFFET(String DEFAULT_TIPO_MESA_BUFFET) {
        this.DEFAULT_TIPO_MESA_BUFFET = DEFAULT_TIPO_MESA_BUFFET;
    }
    public String getDEFAULT_TIPO_MESA_BUFFET() {
        return DEFAULT_TIPO_MESA_BUFFET;
    }
    public void setDEFAULT_TIPO_COBRO_BUFFET(String DEFAULT_TIPO_COBRO_BUFFET) {
        this.DEFAULT_TIPO_COBRO_BUFFET = DEFAULT_TIPO_COBRO_BUFFET;
    }
    public String getDEFAULT_TIPO_COBRO_BUFFET() {
        return DEFAULT_TIPO_COBRO_BUFFET;
    }
    public void setDEFAULT_SERIE_BUFFET(String DEFAULT_SERIE_BUFFET) {
        this.DEFAULT_SERIE_BUFFET = DEFAULT_SERIE_BUFFET;
    }
    public String getDEFAULT_SERIE_BUFFET() {
        return DEFAULT_SERIE_BUFFET;
    }
    public void setDEFAULT_TIPO_SERIE_FACTURA_CLIENTE(String DEFAULT_TIPO_SERIE_FACTURA_CLIENTE) {
        this.DEFAULT_TIPO_SERIE_FACTURA_CLIENTE = DEFAULT_TIPO_SERIE_FACTURA_CLIENTE;
    }
    public String getDEFAULT_TIPO_SERIE_FACTURA_CLIENTE() {
        return DEFAULT_TIPO_SERIE_FACTURA_CLIENTE;
    }

    public int getDEFAULT_VALOR_ON_APERTURA() {
        return DEFAULT_VALOR_ON_APERTURA;
    }
    public void setDEFAULT_VALOR_OFF_APERTURA(int DEFAULT_VALOR_OFF_APERTURA) {
        this.DEFAULT_VALOR_OFF_APERTURA = DEFAULT_VALOR_OFF_APERTURA;
    }
    public int getDEFAULT_VALOR_OFF_APERTURA() {
        return DEFAULT_VALOR_OFF_APERTURA;
    }
    public void setDEFAULT_VALOR_ON_ACTIVO(int DEFAULT_VALOR_ON_ACTIVO) {
        this.DEFAULT_VALOR_ON_ACTIVO = DEFAULT_VALOR_ON_ACTIVO;
    }
    public int getDEFAULT_VALOR_ON_ACTIVO() {
        return DEFAULT_VALOR_ON_ACTIVO;
    }
    public void setDEFAULT_VALOR_OFF_ACTIVO(int DEFAULT_VALOR_OFF_ACTIVO) {
        this.DEFAULT_VALOR_OFF_ACTIVO = DEFAULT_VALOR_OFF_ACTIVO;
    }
    public int getDEFAULT_VALOR_OFF_ACTIVO() {
        return DEFAULT_VALOR_OFF_ACTIVO;
    }

}

